[package]
description = "Smaller & Faster Single-File Vector Search Engine from Unum"
homepage = "https://unum-cloud.github.io/USearch/javascript"
license = "Apache-2.0"
name = "unum/usearch"
readme = "README.md"
repository = "https://github.com/unum-cloud/USearch"
version = "2.25.0"

[[module]]
name = "index"
source = "build/wasm/index.wasm"
