/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cloud_unum_usearch_Index */

#ifndef _Included_cloud_unum_usearch_Index
#define _Included_cloud_unum_usearch_Index
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_create
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_cloud_unum_usearch_Index_c_1create
  (JNIEnv *, jclass, jstring, jstring, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cloud_unum_usearch_Index_c_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cloud_unum_usearch_Index_c_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_connectivity
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cloud_unum_usearch_Index_c_1connectivity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_dimensions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cloud_unum_usearch_Index_c_1dimensions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_capacity
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cloud_unum_usearch_Index_c_1capacity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_reserve
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cloud_unum_usearch_Index_c_1reserve
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_add
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_cloud_unum_usearch_Index_c_1add
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_search
 * Signature: (J[FJ)[I
 */
JNIEXPORT jintArray JNICALL Java_cloud_unum_usearch_Index_c_1search
  (JNIEnv *, jclass, jlong, jfloatArray, jlong);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_save
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cloud_unum_usearch_Index_c_1save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_load
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cloud_unum_usearch_Index_c_1load
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_view
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cloud_unum_usearch_Index_c_1view
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_remove
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_cloud_unum_usearch_Index_c_1remove
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cloud_unum_usearch_Index
 * Method:    c_rename
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_cloud_unum_usearch_Index_c_1rename
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
